LPS-110408 add ManagementToolbar, test ids and test and  SF
brunofarache/liferay-portal pull request #120
Opened 2020-03-17 17:37 UTC by kevenleone

2020-03-18 02:08 UTC, brunofarache commented
Just started reviewing :)

2020-03-18 13:14 UTC, brunofarache requested changes

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/management-toolbar/ManagementToolbarRight.es.js
> +					data-testid="toggleMobileToolbarRight"
@kevenleone tentar remover testid

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/management-toolbar/ManagementToolbarSearch.js
> +							data-testid="submitSearchInput"
@kevenleone tentar remover testid

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/list-view/ListView.es.js
> +		await act(async () => {
@kevenleone checar se await é preciso mesmo.

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/list-view/ListView.es.js
> +		await act(async () => {
@kevenleone checar se await é preciso mesmo.

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/management-toolbar/ManagementToolbar.es.js
> +		cleanup();
@kevenleone faltando o restoreMockups

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/management-toolbar/ManagementToolbar.es.js
> +		const onClickButton = jest.fn();
onClickButtonCallback

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/management-toolbar/ManagementToolbar.es.js
> +				key: 'Date Modified',
Modified Date

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/management-toolbar/ManagementToolbar.es.js
> +		const dropdown = queryByText('filter-and-order');
dropDown?

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/management-toolbar/ManagementToolbar.es.js
> +		expect(queryByText('Date Modified')).toBeFalsy();
Modified Date

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/utils/client.es.js
> +		jest.clearAllMocks();
o certo é restore.

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/management-toolbar/ManagementToolbar.es.js
> +				key: 'Date Modified',
Ou qualquer valor ("key"), não precisa ser muito criativo nesses valores.

2020-03-18 13:14 UTC, brunofarache commented on modules/apps/app-builder/app-builder-web/test/js/components/management-toolbar/ManagementToolbar.es.js
> +	it('render with props', async () => {
se retirar todos os awaits o async nao é mais necessário

2020-03-18 17:28 UTC, kevenleone commented
Pull requests updated with requested adjustments

2020-03-19 14:23 UTC, brunofarache commented
Just started reviewing :)

2020-03-19 14:55 UTC, brunofarache commented
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86547. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/94a8dc616a41~1...94a8dc616a41)

2020-03-19 14:55 UTC, closed without merging