LPS-111789 Update refs to be accessible to tests
brunofarache/liferay-portal pull request #169
Opened 2020-04-15 17:59 UTC by alinedoleron

2020-04-15 17:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-04-16 11:17 UTC, brunofarache requested changes

2020-04-16 11:17 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/FormRenderer/FormRenderer.es.js
> +	it('renders default markup with Success Page ative', () => {
typo no `ative`, seria `active`, ou melhor `enabled`.

2020-04-16 11:17 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/FormRenderer/FormRenderer.es.js
> +			portletNamespace: 'portletNamespace',
metal tem o mesmo conceito de Context do React? portletNamespace deveria fazer parte de um contexto em vez de ser requerido como prop em todo canto?

2020-04-16 11:17 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/PageRenderer/PageRenderer.es.js
> +		jest.useFakeTimers();
useFakeTimers() foi chamado duas vezes, precisa mesmo?

`pagesEmpty` e `sucessPageSettings` precisam ser recriados realmente toda vez antes de cada teste? Poderiam ser constantes criadas uma vez apenas não?

2020-04-16 11:17 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/PageRenderer/PageRenderer.es.js
> +const spritemap = 'icons.svg';
por que apenas spritemap virou constante?

vários valores se repetem em todos os testes e não viraram constantes:

editingLanguageId: 'en_US',
paginationMode: 'wizard',
portletNamespace: 'portletNamespace',
etc.

Em vez de criar varias constantes, eu faria uma função de factory para PageRendererWithContextMock e usaria em todos os testes:

```
const createPageRenderer = (props) => {
		return new PageRendererWithContextMock({
			editable: true,
			editingLanguageId: 'en_US',
			page: pagesEmpty[0],
			pageIndex: 0,
			pages: pagesEmpty,
			paginationMode: 'wizard',
			portletNamespace: 'portletNamespace',
			showSubmitButton: false,
			spritemap,
			submitLabel: 'Submit',
			successPageSettings,
			total: 2,
			view: 'formBuilder',
                         {...props}
		});
};
```

2020-04-16 11:17 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/SuccessPage/SuccessPage.es.js
> +		const SuccessPageWithContextMock = withContextMock(SuccessPage);
Extrairia esse linha de criação do SuccessPage mockado para uma função também, visto que é usado em todos os testes.

2020-04-16 11:17 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/SuccessPage/SuccessPage.es.js
> +		successPageSettings = null;
Desncessário setar para null, visto que é recriado no beforeEach.

2020-04-16 11:17 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/js/components/PageRenderer/PageRenderer.soy
> +						{param ref: 'successPageActions' + $pageIndex /}
Me explica o motivo disso ser necessário, por favor.

2020-04-16 17:04 UTC, alinedoleron commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2020-04-16 17:22 UTC, alinedoleron commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/FormRenderer/FormRenderer.es.js
> +			portletNamespace: 'portletNamespace',
Não sei te dizer. O componente do FormRenderer recebe como props. Para o teste não influencia no resultado, mas é que aparece no console o erro quando rodo os testes.

2020-04-16 17:27 UTC, alinedoleron commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/PageRenderer/PageRenderer.es.js
> +		jest.useFakeTimers();
**pagesEmpty** e **sucessPageSettings** precisam ser recriados pois em alguns testes eu faço alterações em suas propriedades.

2020-04-16 19:50 UTC, alinedoleron commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/test/js/components/PageRenderer/PageRenderer.es.js
> +const spritemap = 'icons.svg';
Massa. Dei uma enxugada fazendo isso. Mas vou precisar passar os dados de page, pageIndex e pages pq eles variam dependendo do teste.

2020-04-16 20:35 UTC, alinedoleron commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/js/components/PageRenderer/PageRenderer.soy
> +						{param ref: 'successPageActions' + $pageIndex /}
Ele é uma referência para, por exemplo, eu verificar se o componente das actions do Success Page está presente. Adicionei mais dois testes para verificar isso para página normal e página de sucesso.

2020-04-16 21:12 UTC, alinedoleron commented
The pr with the changes requested is: https://github.com/brunofarache/liferay-portal/pull/173.

2020-04-16 21:12 UTC, closed without merging