LPS-114278 create a custom hook to get a field value from all form records
brunofarache/liferay-portal pull request #324
Opened 2020-05-27 18:35 UTC by marcosapmf

2020-05-27 18:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-05-27 20:26 UTC, alinedoleron commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2020-05-28 11:12 UTC, brunofarache requested changes
muito bom @marcosapmf. apenas alguns detalhes descritos abaixo. pode usar o mesmo PR para atualizar.

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/resources/META-INF/resources/js/utils/formInstanceRecordsFieldValues.es.js
> +import {useResource} from '@clayui/data-provider';
@marcosapmf tivemos alguns problemas com esse componente no passado, melhor usar algo mais simples como:

https://github.com/brunofarache/liferay-portal/blob/master/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/hooks/useRequest.es.js

o useResource tem muitas features que não usamos, como caching e refetch, que faz com que as coisas se compliquem um pouco quando começamos a usá-lo.

vou remover esse hook e @alinedoleron poderá usar o useRequest, basta ela saber qual a query que deve fazer a request, que está abaixo.

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/java/com/liferay/dynamic/data/mapping/form/report/web/internal/display/context/DDMFormReportDisplayContext.java
> +		resourceURL.setResourceID("/forms/records/field/value");
@marcosapmf resourceURL muito extenso, sem necessidade, não é uma API rest. Checar como são os outros resourceURLs por aí. eu colocaria apenas `/formRecords`.

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/resources/META-INF/resources/init.jsp
> +<aui:script>
@marcosapmf para que serveria isso? quando queremos pasar o portlet namespace ou coisa parecida, passamos como prop no jsp que inicia o react e adicionamos a um AppContext como este:

https://github.com/brunofarache/liferay-portal/blob/master/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/AppContext.es.js

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/resources/META-INF/resources/init.jsp
> +<aui:script>
ah, acho que é usado para o useResource? como vai ser eliminado, deixa @alinedoleron fazer o AppContext.

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/java/com/liferay/dynamic/data/mapping/form/report/web/internal/action/FormInstanceRecordsFieldValueMVCResourceCommand.java
> +		for (DDMFormInstanceRecord formInstanceRecord : formInstanceRecords) {
@marcosapmf talvez usar a API de stream para converter de lista para jsonArray seja mais compacto.

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/java/com/liferay/dynamic/data/mapping/form/report/web/internal/action/FormInstanceRecordsFieldValueMVCResourceCommand.java
> +		"mvc.command.name=/forms/records/field/value"
@marcosapmf ajeitar path como descrito abaixo.

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/java/com/liferay/dynamic/data/mapping/form/report/web/internal/action/FormInstanceRecordsFieldValueMVCResourceCommand.java
> +			for (DDMFormFieldValue ddmFormFieldValue : ddmFormFieldValues) {
@marcosapmf não acho que deveríamos colocar todos os valores de todos os fields. deveria ser apenas os valores do field em questão. por exemplo, se quero ter uma lista de todos os first names, deveria vir um jsonArray apenas contendo first name e não todos outros campos, o payload vai ficar muito maior se colocarmos todos campos na response.

2020-05-28 11:12 UTC, brunofarache commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/java/com/liferay/dynamic/data/mapping/form/report/web/internal/action/FormInstanceRecordsFieldValueMVCResourceCommand.java
> +			httpServletRequest, "end", QueryUtil.ALL_POS);
@marcosapmf entendo que essa task combinamos de retornar todos as linhas, sem paginação. se liga que quando adicionarmos paginação, o usuário não vai poder passar o `end` como parâmetro pois somos nós quem decidimos  o tamanho da página e não o client. o problema de deixar o usuário pegar todos as rows, é que pode deixar o servidor lento e dar denial of service caso existam milhares de records.

2020-05-29 05:09 UTC, alinedoleron commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2020-05-29 10:46 UTC, brunofarache commented
Just started reviewing :)

2020-05-29 11:28 UTC, marcosapmf commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-report-web/src/main/java/com/liferay/dynamic/data/mapping/form/report/web/internal/action/FormInstanceRecordsFieldValueMVCResourceCommand.java
> +			for (DDMFormFieldValue ddmFormFieldValue : ddmFormFieldValues) {
@brunofarache , aqui eu estou pegando só os valores do field que vem no parâmetro. Assim:
```
List<DDMFormFieldValue> ddmFormFieldValues =
				ddmFormFieldValuesMap.get(fieldName);
```
A questão é que a API do field suporta multiplos valores, por isso ele retorna uma lista.

2020-05-29 11:44 UTC, brunofarache commented
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/331.

2020-05-29 11:44 UTC, closed without merging

2020-05-29 11:50 UTC, brunofarache commented
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/332. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/793cd4551b7e~1...793cd4551b7e)

2020-05-29 11:59 UTC, brunofarache commented
Pull request submitted to https://github.com/brunofarache/liferay-portal/pull/333. [See changes here.](https://github.com/brunofarache/liferay-portal/compare/897e54df5202~1...897e54df5202)